### ISSUE TITLE
Currently broken on windows

### ISSUE THREAD

**Issue by Mutnick** [eLvErDe/nicotine-plus#18]
Traceback (most recent call last):
  File "nicotine.py", line 36, in <module>
    ApplyTranslation()
  File "Z:\dev\new\nicotine-plus-master\pynicotine\utils.py", line 144, in ApplyTranslation
    currentlang = locale.getlocale()[0].split('_')[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by gfarmerfr** [comment]
Hi thx for the bug report.

I was aware of that: i need to fix translations / locales and a pile of encoding related stuff on windows. I'm beginning to understand why the windows installer for 1.2.16 was only in english :)

I was playing around with my win7 VM with python 2.7 and msys2 + all the required dependencies and i found a couple of bugs:
* The first one was yours :). I wiil probably fix it soon.
* The second one was that in python 2.7 the 'shelve' module used to read/write lots of db files dropped a lot of possibles backends and something is going wrong at the first install in config.py. This one might take some time.
* After commenting out a lot of stuff finally the UI launches but any accentuated characters is shown as a box is the menus / tabs but not in the chats, etc... Something tells me glade2 is the faulty part: i'm beginning to switch to gtk.builder. This one will take some time too but hopefully we will have a translatable UI on windows...

Anyway there is a lot of things to cleanup/update before even thinking of packaging stuff on windows. If I were you I won't run the git master version without backing up my config files before :).

I'm also wondering what method to use to package the windows build since the last gtk+ 2.24 build is not available as a bundle like in old times.
It will be either:
* pyinstaller for a 'freezed' build: https://github.com/pyinstaller/pyinstaller
* something based on msys2: https://msys2.github.io/

**Comment by Mutnick** [comment]
I'm thinking that code known to be broken should not be merged into the master branch. It is trivial to create other branches.

**Comment by gfarmerfr** [comment]
I tend to agree with you.
I will revert some of the changes to make it work on windows.

**Comment by gfarmerfr** [comment]
btw which version on windows / python are you running ?

**Comment by gfarmerfr** [comment]
Could you check if this branch fix the problem ? Thx.
https://github.com/gfarmerfr/nicotine-plus/tree/fix-windows-build
I've included the instruction to run from git in doc/RUNFROMGIT.md on this branch.

Also it seems that the two other bugs (shelve module borked and weird characters in the UI) don't appears if I install python, gtk+ and pygtk from their respective sources.
Something seems broken with the packages included in msys2 or i'm missing something.

**Comment by gfarmerfr** [comment]
Hi @Mutnick : i've just updated my branch.
Translations and locales were already working with the previous commit.
I've fixed the code further to be able to switch between locales / translations on Windows.
Tested both under my Win7 box and Fedora.

**Comment by Mutnick** [comment]
This particular issue appears to be fixed in the branch you linked.

**Comment by gfarmerfr** [comment]
thx for the confirmation: fix committed to master.
